### ISSUE TITLE
Mapping of values in build2

### ISSUE THREAD

**Issue by Rookfighter** [build2-packaging/nng#1]
Hi @boris-kolpackov,

I wonder if there is a way of employing some kind of mapping between two lists of values in build2. If you have a look at [these lines](https://github.com/build2-packaging/nng/blob/master/libnng/src/buildfile#L34) I check for a specific flag and add a poption if it is true. I would really like to do something like this:

```
config_flags = $config.libnng.use_x $config.libnng.use_y # etc.
config_poptions = NNG_USE_X NNG_USE_y # etc.
for (i = 0; i < length(config_flags); ++i)
{
    if ($config_flags[i])
    {
        c.poptions += -D$config_poptions[i]
    }
}
```

Or similar behaviour with a list of pairs, I don't mind.

Is this currently possible? I could not find any example of this.

**Comment by boris-kolpackov** [comment]
This is possible but only in `0.16.0`. Here is an example of pretty much the same thing (it's inside a recipe so replace `if/for...end` with `if/for{...}`): https://github.com/build2/cherimcu/blob/master/build/cherimcu.build#L249-L260

The `0.16.0` release is only a few months out so if you would like to use this, I would suggest that you submit your package to https://queue.stage.build2.org instead of https://queue.cppget.org (`bdep publish --repository=https://stage.build2.org ...`). Once `0.16.0` is out we will automatically move it to cppget.org. As you can see, we have quite a few packages accumulated there.

**Comment by Rookfighter** [comment]
Thanks, using 0.16.0 with arrays worked like a charm and makes things much easier :+1:
