### ISSUE TITLE
Issues in the submited 1.5.2 package

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/nng#3]
Noticed a couple of issues:

1. `build/root.build` lines 23-25: I believe these config values are integers and using `uint64` instead of `string` would be a good idea.

2. `build/root.build` line 54: I believe `'mbdedtls'` should be `'mbedtls'`.

3. `src/buildfile` line 154: `c.target.class` for FreeBSD, NetBSD, and OpenBSD is `bsd` so this won't do what you expect (and you see some configure warnings on CI to this effect). The easiest way to fix this is probably to switch on both class and system and then match `bsd`, `freebsd`, etc. The manual has an example: https://build2.org/build2/doc/build2-build-system-manual.xhtml#intro-switch

I think these warrant a revision so I will wait before publishing.

**Comment by Rookfighter** [comment]
Thanks for the feedback. I fixed the issues and will submit a new revision.

Regarding point 3: Is there a list / table available of the values for `*.target.*` variables? I was not able to find anything like that on build2.org (Build System Manual and Package Manager Manual are usually my first resources to look at) but maybe I just did not see it.
I happen to struggle with platform specific switch-cases from time to time, because I cannot remember the correct strings for matching target.system and target.class. Usually I have to look in other package repositories to get some inspiration.

**Comment by boris-kolpackov** [comment]
> Is there a list / table available of the values for `*.target.*` variables?

The progenitor of the `*.target.*` variables is the `target_triplet` class and its documentation is for now the best source of this information: https://github.com/build2/libbutl/blob/master/libbutl/target-triplet.hxx#L66-L102

But I agree, we need to document this in the manual and I've added a TODO item to my list.

**Comment by Rookfighter** [comment]
Thanks for the link :+1: Added to my build2 bookmarks
